title: Stanford Boilerplate
description: |
  This is a bunch of boilerplate
author: Dan Nguyen
image_url: /assets/images/logo.png
baseurl: "http://www.example.com"


# services:
#   google_analytics:
#     id: UA-XXXXX
